hw6
bardaev/inno_task pull request #1
Opened 2020-12-03 09:05 UTC by bardaev

2020-12-04 16:23 UTC, maximusKon requested changes

2020-12-04 16:23 UTC, maximusKon commented on src/main/java/part1/lesson06/task01/CleanUp.java
> +    private void mapCleanOutput(Object object, Set<String> fieldsToCleanUp, Set<String> fieldsToOutput) {
Почему не просто mapClean ?

2020-12-04 16:23 UTC, maximusKon commented on src/main/java/part1/lesson06/task01/CleanUp.java
> +            fieldCleanUp(object, fieldsToCleanUp, cl);
В эти функции нет смысла передавать отдельно cl, вполне можно ограничиться object. Стремитесь к тому, чтобы уменьшать количество аргументов функций когда возможно.

2020-12-04 16:23 UTC, maximusKon commented on src/main/java/part1/lesson06/task01/CleanUp.java
> +    private boolean isMap(Class<?>[] c) {
Хорошая решение, но избегайте называть переменные буквами. В данном случае можно назвать interfaces, а саму функцию containsMap, так как вы перибератете массив.

2020-12-04 16:23 UTC, maximusKon commented on src/main/java/part1/lesson06/task01/CleanUp.java
> +            } catch (NoSuchFieldException | IllegalAccessException e) {
IllegalAccessException не говорит о том, что нет филда, его лучше пробросить выше. Плюс заметьте, вас просят оставить объект неизменным, если какого-то филда нет, однако в данном случае, все поля, которые вы уже успели очистить остануться с с очищенными значениями.

2020-12-04 16:23 UTC, maximusKon commented on src/main/java/part1/lesson06/task01/CleanUp.java
> +                throw new IllegalArgumentException("Field not exist");
Всегда старайтесь сообщать максимально много информации, из вашей ошибки не будет ясно, в каком поле проблема.

2020-12-04 16:23 UTC, maximusKon commented on src/test/java/part1/lesson06/task01/CleanUpTest.java
> +class CleanUpTest {
Не хватает негативного теста на очистку мапы и нет тестов на изменения. А так очень здорово, что написали 🙂

2020-12-05 13:18 UTC, bardaev commented on src/main/java/part1/lesson06/task01/CleanUp.java
> +    private void mapCleanOutput(Object object, Set<String> fieldsToCleanUp, Set<String> fieldsToOutput) {
Потому что метод выполняет и чистку и вывод

2020-12-05 13:21 UTC, bardaev commented on src/main/java/part1/lesson06/task01/CleanUp.java
> +            fieldCleanUp(object, fieldsToCleanUp, cl);
Исправил

2020-12-05 13:22 UTC, bardaev commented on src/main/java/part1/lesson06/task01/CleanUp.java
> +    private boolean isMap(Class<?>[] c) {
исправил

2020-12-05 14:26 UTC, bardaev commented on src/main/java/part1/lesson06/task01/CleanUp.java
> +            } catch (NoSuchFieldException | IllegalAccessException e) {
Исправил

2020-12-05 14:26 UTC, bardaev commented on src/main/java/part1/lesson06/task01/CleanUp.java
> +                throw new IllegalArgumentException("Field not exist");
Исправил

2020-12-05 19:40 UTC, maximusKon approved these changes
В целом всё хорошо, но обратите внимания на комментарии.

2020-12-05 19:40 UTC, maximusKon commented on src/main/java/part1/lesson06/task01/CleanUp.java
> +    private void mapCleanOutput(Object object, Set<String> fieldsToCleanUp, Set<String> fieldsToOutput) {
Я бы в таком случае разделили на две функции аналогично fieldCleanUp и fieldOutput для единообразия и сингл-респонсибилиси.

2020-12-05 19:40 UTC, maximusKon commented on src/main/java/part1/lesson06/task01/CleanUp.java
> +                throw new IllegalArgumentException();
Вот это совсем ни о чём не говорит. В чём конкретно проблема? как минимум нужно передавать исключение e качестве cause, ну и текст должен быть всегда в обязательном порядке. Хотя бы "Exception while reading field <имя филда>". И тогда уже посмотрев на cause исключение можно сделать определённый вывод.

2020-12-05 19:51 UTC, merged